version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      retries: 10

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snake_game
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      DISPLAY: ":99"  # Update to use the virtual display created by Xvfb
      MONGO_URI: mongodb:/  # Update the MongoDB URI as needed